import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");

// Turkish word replacements (ASCII -> proper Turkish)
const replacements = [
  // Common words
  ["Turkiye", "Türkiye"],
  ["turkiye", "türkiye"],
  ["guzellik", "güzellik"],
  ["Guzellik", "Güzellik"],
  ["guzel", "güzel"],
  ["dogal", "doğal"],
  ["Dogal", "Doğal"],
  ["doga", "doğa"],
  ["Doga", "Doğa"],
  ["bolge", "bölge"],
  ["Bolge", "Bölge"],
  ["Bolgesi", "Bölgesi"],
  ["bolgenin", "bölgenin"],
  ["bolgesi", "bölgesi"],
  ["bolgedeki", "bölgedeki"],
  ["bolgenin", "bölgenin"],
  ["yuruyus", "yürüyüş"],
  ["Yuruyus", "Yürüyüş"],
  ["yuksek", "yüksek"],
  ["Yuksek", "Yüksek"],
  ["yukselen", "yükselen"],
  ["yuksekligi", "yüksekliği"],
  ["yukseklik", "yükseklik"],
  ["yukseklikte", "yükseklikte"],
  ["ulasim", "ulaşım"],
  ["Ulasim", "Ulaşım"],
  ["ulasam", "ulaşam"],
  ["goller", "göller"],
  ["Goller", "Göller"],
  ["golleri", "gölleri"],
  ["gollerin", "göllerin"],
  ["golun", "gölün"],
  ["Golu", "Gölü"],
  ["golu", "gölü"],
  ["Golcuk", "Gölcük"],
  ["gorunum", "görünüm"],
  ["gorsel", "görsel"],
  ["goruntus", "görüntüs"],
  ["goruntuleyici", "görüntüleyici"],
  ["Goruntulle", "Görüntüle"],
  ["gorunus", "görünüş"],
  ["gormeniz", "görmeniz"],
  ["gorur", "görür"],
  ["gorunur", "görünür"],
  ["gorunebilir", "görünebilir"],
  ["gorunmeli", "görünmeli"],
  ["gormeli", "görmeli"],
  ["gorulen", "görülen"],
  ["gorulmesi", "görülmesi"],
  ["gorece", "görece"],
  ["gosterir", "gösterir"],
  ["gosteriyor", "gösteriyor"],
  ["gonderi", "gönder"],
  ["gonderme", "gönderme"],
  ["gonderil", "gönderil"],
  ["Gonder", "Gönder"],
  ["gonder", "gönder"],
  ["donusum", "dönüşüm"],
  ["donus", "dönüş"],
  ["Donus", "Dönüş"],
  ["donemler", "dönemler"],
  ["donem", "dönem"],
  ["Dort", "Dört"],
  ["dort", "dört"],
  ["oneri", "öneri"],
  ["Oneri", "Öneri"],
  ["onerilen", "önerilen"],
  ["Onerilen", "Önerilen"],
  ["oneriler", "öneriler"],
  ["onerisi", "önerisi"],
  ["oncelik", "öncelik"],
  ["onceden", "önceden"],
  ["once", "önce"],
  ["Once", "Önce"],
  ["onemli", "önemli"],
  ["Onemli", "Önemli"],
  ["ozellik", "özellik"],
  ["Ozellik", "Özellik"],
  ["ozel", "özel"],
  ["Ozel", "Özel"],
  ["ozellikle", "özellikle"],
  ["Ozellikle", "Özellikle"],
  ["ozgun", "özgün"],
  ["otesi", "ötesi"],
  ["olcek", "ölçek"],
  ["olmaz", "olmaz"],
  ["olcum", "ölçüm"],
  ["ornek", "örnek"],
  ["Ornek", "Örnek"],
  ["ornekleri", "örnekleri"],
  ["ozet", "özet"],
  ["yoresel", "yöresel"],
  ["Yoresel", "Yöresel"],
  ["yore", "yöre"],
  ["yonetim", "yönetim"],
  ["Yonetim", "Yönetim"],
  ["icerik", "içerik"],
  ["Icerik", "İçerik"],
  ["icinde", "içinde"],
  ["icin", "için"],
  ["Icin", "İçin"],
  ["icine", "içine"],
  ["iceri", "içeri"],
  ["iceren", "içeren"],
  ["icermeli", "içermeli"],
  ["iletisim", "iletişim"],
  ["Iletisim", "İletişim"],
  ["iliskili", "ilişkili"],
  ["inceleme", "inceleme"],
  ["islem", "işlem"],
  ["isleme", "işleme"],
  ["islendigi", "işlendiği"],
  ["islenmis", "işlenmiş"],
  ["islenme", "işlenme"],
  ["istegi", "isteği"],
  ["istek", "istek"],
  ["istediginiz", "istediğiniz"],
  ["ucretsiz", "ücretsiz"],
  ["Ucretsiz", "Ücretsiz"],
  ["ucret", "ücret"],
  ["ucuz", "ucuz"],
  ["uretim", "üretim"],
  ["uretilen", "üretilen"],
  ["urun", "ürün"],
  ["urunler", "ürünler"],
  ["Urun", "Ürün"],
  ["cesitli", "çeşitli"],
  ["cesit", "çeşit"],
  ["cevre", "çevre"],
  ["Cevre", "Çevre"],
  ["cevresinde", "çevresinde"],
  ["cevresindeki", "çevresindeki"],
  ["cerez", "çerez"],
  ["Cerez", "Çerez"],
  ["cicek", "çiçek"],
  ["Cicek", "Çiçek"],
  ["coskun", "coşkun"],
  ["cuskun", "coşkun"],
  ["cocuk", "çocuk"],
  ["Cocuk", "Çocuk"],
  ["calisman", "çalışman"],
  ["calisiyor", "çalışıyor"],
  ["calisma", "çalışma"],
  ["Calisma", "Çalışma"],
  ["calisir", "çalışır"],
  ["cikan", "çıkan"],
  ["cikar", "çıkar"],
  ["cikin", "çıkın"],
  ["cikis", "çıkış"],
  ["Cikis", "Çıkış"],
  ["degisken", "değişken"],
  ["degistikce", "değiştikçe"],
  ["degisebilir", "değişebilir"],
  ["degisiklik", "değişiklik"],
  ["degisen", "değişen"],
  ["degil", "değil"],
  ["deger", "değer"],
  ["degerli", "değerli"],
  ["disinda", "dışında"],
  ["disina", "dışına"],
  ["disi", "dışı"],
  ["Dusuk", "Düşük"],
  ["dusuk", "düşük"],
  ["duser", "düşer"],
  ["dusebilir", "düşebilir"],
  ["duzenli", "düzenli"],
  ["duzgun", "düzgün"],
  ["Duz", "Düz"],
  ["genis", "geniş"],
  ["gecis", "geçiş"],
  ["gecisi", "geçişi"],
  ["gecmis", "geçmiş"],
  ["gider", "gider"],
  ["Gidilir", "Gidilir"],
  ["gunduz", "gündüz"],
  ["gunluk", "günlük"],
  ["guncel", "güncel"],
  ["guncelleme", "güncelleme"],
  ["gunes", "güneş"],
  ["Gunes", "Güneş"],
  ["guvenlik", "güvenlik"],
  ["Guvenlik", "Güvenlik"],
  ["guvenli", "güvenli"],
  ["guven", "güven"],
  ["hizli", "hızlı"],
  ["Hizli", "Hızlı"],
  ["hizmet", "hizmet"],
  ["Hakkinda", "Hakkında"],
  ["hakkinda", "hakkında"],
  ["hatirla", "hatırla"],
  ["kisim", "kısım"],
  ["kis", "kış"],
  ["Kis", "Kış"],
  ["kisi", "kişi"],
  ["kisisel", "kişisel"],
  ["Kisisel", "Kişisel"],
  ["kisilik", "kişilik"],
  ["kaldir", "kaldır"],
  ["kaydir", "kaydır"],
  ["karsi", "karşı"],
  ["karsilastirma", "karşılaştırma"],
  ["kosul", "koşul"],
  ["kosullar", "koşullar"],
  ["Konaklama", "Konaklama"],
  ["konaklama", "konaklama"],
  ["musteri", "müşteri"],
  ["mumkun", "mümkün"],
  ["Mumkun", "Mümkün"],
  ["mukemmel", "mükemmel"],
  ["Nasil", "Nasıl"],
  ["nasil", "nasıl"],
  ["pistleri", "pistleri"],
  ["restoranlar", "restoranlar"],
  ["sehir", "şehir"],
  ["Sehir", "Şehir"],
  ["sezon", "sezon"],
  ["sicaklik", "sıcaklık"],
  ["sicak", "sıcak"],
  ["sinir", "sınır"],
  ["sinirli", "sınırlı"],
  ["sunan", "sunan"],
  ["suren", "süren"],
  ["surer", "sürer"],
  ["surme", "sürme"],
  ["surus", "sürüş"],
  ["tabiat", "tabiat"],
  ["tanitir", "tanıtır"],
  ["taninir", "tanınır"],
  ["taninmis", "tanınmış"],
  ["tercihi", "tercihi"],
  ["turizm", "turizm"],
  ["Turizm", "Turizm"],
  ["yakin", "yakın"],
  ["Yakin", "Yakın"],
  ["yakinlik", "yakınlık"],
  ["yillik", "yıllık"],
  ["yil", "yıl"],
  ["Yil", "Yıl"],
  ["yogun", "yoğun"],
  ["yogunluk", "yoğunluk"],
  ["yukari", "yukarı"],
  ["zorunlu", "zorunlu"],
];

// Files to process
function getFiles(dir, exts) {
  let results = [];
  const items = fs.readdirSync(dir);
  for (const item of items) {
    const full = path.join(dir, item);
    if (item === "node_modules" || item === ".next" || item === ".git") continue;
    const stat = fs.statSync(full);
    if (stat.isDirectory()) {
      results = results.concat(getFiles(full, exts));
    } else if (exts.some(e => full.endsWith(e))) {
      results.push(full);
    }
  }
  return results;
}

const files = getFiles(root, [".tsx", ".ts", ".md", ".txt"]);
let totalChanges = 0;

for (const file of files) {
  // Skip this script itself and node_modules paths
  if (file.includes("fix-turkish") || file.includes("node_modules")) continue;

  let content = fs.readFileSync(file, "utf-8");
  let original = content;

  for (const [from, to] of replacements) {
    // Only replace in string content, not in variable names or CSS classes
    // Use word boundary matching
    const regex = new RegExp(`\\b${from}\\b`, "g");
    content = content.replace(regex, to);
  }

  if (content !== original) {
    fs.writeFileSync(file, content, "utf-8");
    totalChanges++;
    console.log(`Fixed: ${path.relative(root, file)}`);
  }
}

console.log(`\nTotal files changed: ${totalChanges}`);
